apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: binder-harbor-push
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: binder-harbor-push
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        config.json: |
          {
            "auths": {
              "hub.k8s.ucar.edu": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
        build_token_secret: "{{ .build_token_secret }}"
  data:
    - secretKey: username
      remoteRef:
        key: team-cirrus/binder
        property: username
    - secretKey: password
      remoteRef:
        key: team-cirrus/binder
        property: password
    - secretKey: build_token_secret
      remoteRef:
        key: team-cirrus/binder
        property: build_token
